@startuml
title DFD As-Is: Запись и обслуживание пациента

actor "Пациент" as Patient

rectangle "Запись на приём\n(ресепшен)" as P1
rectangle "Ведение медкарты\n(врач)" as P2

database "Журнал записей\n(Excel на общем диске)" as D1
database "Медкарты\n(сканы JPG/PDF\nна общем диске)" as D2
database "Анкеты пациента\n(Excel/сканы)" as D3

Patient --> P1 : Анкетные данные\nPII + расширенные PII + часть PHI
P1 --> D1 : Запись на приём\nФИО, телефон, дата, врач (PII)
P1 --> D3 : Анкета пациента\nадрес, работа/учёба,\nхронические заболевания (PII+PHI)

Patient --> P2 : Жалобы, анамнез (PHI)
P2 --> D2 : Медкарта\nдиагнозы, назначения,\nрезультаты анализов (PHI)
P2 --> D3 : Обновлённая анкета/история\n(PII+PHI)

@enduml